NAMING_PREFIX = 'AUTO_GENERATE '

MATERIAL_CODE = 'SKU1001'
MATERIAL_SUPPLIER = 'SUP-01HKYT27W8BYB2EY3BX3D6F5TF'
MATERAIL_VENDOR = ''

WAREHOUSE_CAPACITY = 100000
WAREHOUSE_MATERIAL_LOAD_QUANTITY = 100000
WAREHOUSE_LEVELS = 2  # 2 level warehouses[Transit, store].
                      # 3 level warehouse [Transit, Transit, store]

NUMBER_OF_RACKS = '5'
RACK_CAPACITY = '20'

WAREHOUSE_ROOT_NAME = 'Root'
WAREHOUSE_STORE_NAME = 'Store'
WAREHOUSE_INTERNAL_NODE_NAME = 'Transit Level'