NAMING_PREFIX = 'AUTO_GENERATE '

COMPANY_NAME = 'Company'
MATERIAL_CODE = 'SKU1001'
MATERIAL_SUPPLIER = 'SUP-01HQB0BBV4JT21KFW4500QRGKG'
MATERIAL_VENDOR = 'VEN-01HQB0X2VZQV34HABJZ6AKG416'

WAREHOUSE_CAPACITY = 100000
MATERIAL_LOAD_QUANTITY = 500
MATERIAL_LOAD_PRICE = 3110000

# Warehouse Levels
# 2 level warehouses[Transit, store].
# 3 level warehouse [Transit, Transit, store]
WAREHOUSE_LEVELS = 2

NUMBER_OF_RACKS = '5'
RACK_CAPACITY = '20'

WAREHOUSE_ROOT_NAME = 'Root'
WAREHOUSE_STORE_NAME = 'Store'
WAREHOUSE_INTERNAL_NODE_NAME = 'Transit Level'
