NAMING_PREFIX = 'FLOW_TEST '

COMPANY_NAME = 'Integration-Company'
MATERIAL_CODE = 'SKU1001'
MATERIAL_SUPPLIER = 'SUP-01HR4DA3BHBAQRJR9B2FK8MBKZ'
MATERIAL_VENDOR = 'VEN-01HR4DKE0TX30GJHDMK2FG64CV'

WAREHOUSE_CAPACITY = 100000
MATERIAL_LOAD_QUANTITY = 500
MATERIAL_LOAD_PRICE = 6200

# Warehouse Levels
# 2 level warehouses[Transit, store].
# 3 level warehouse [Transit, Transit, store]
WAREHOUSE_LEVELS = 2

NUMBER_OF_RACKS = '5'
RACK_CAPACITY = '20'

WAREHOUSE_ROOT_NAME = 'Root'
WAREHOUSE_STORE_NAME = 'Store'
WAREHOUSE_INTERNAL_NODE_NAME = 'Transit Level'
